### PR TITLE
Server Config / Character Creation

### PR DESCRIPTION
**Pull request by jehgo**
**Changes**
* Two new tables added to the World db, server_config and server_config_character_creation_location
   * Migration has been added and should auto generate the tables and populate them with basic required info
* New column added onto the character table of the Character db, rotationX
* Updated Game/AssetManager to cache XP values from the game tables
* Updated Handler/CharacterHandler to correctly apply the appropriate character level depending on if Novice or Veteran start is selected. 
* Updated Handler/CharacterHandler to set the starting location for reach character to the appropriate location based on Novice/Veteran selection and Race, including the direction the character faces
* Updated Entity/Player to include
   * Setting of rotation in constructor
   * Setting of yaw in AddToMap
   * Saving of rotationX in Save
~~Also includes fix for CharacterDatabase to correctly load costume items, mail items and quest objectives upon user login~~ (logged separately as #290)

**Known issues to be investigated/resolved**
None atm

### CODE REVIEW

**Comment by MaxtorCoder** [comment]
Isn't there supposed to be a Orientation field as well? Or am I mistaken.

**Comment by MaxtorCoder** [comment]
Also please split the fixes into new PRs. Better organization and all. :)

**Comment by jehgo** [comment]
> Isn't there supposed to be a Orientation field as well? Or am I mistaken.

Yup, still to be done but want to get the basis of the implementation up for people to check over and highlight any glaring problems that need to be addressed

> Also please split the fixes into new PRs. Better organization and all. :)

You're right, I'll do that separately now
Edit: Logged as #290, force pushing commit without the hotfix in it for now

**Comment by jehgo** [comment]
Updated to include a migration of the character database to enable character rotation to be set and retained, as well as the necessary code to enable the functionality

**Pull request closed without merging**
