### PR TITLE
Fixed pet summoning

### PR DESCRIPTION
**Pull request by ChargeIn**
Fixed a null pointer on pet summon due to the id not being set.

### CODE REVIEW

**Comment by Rawaho** [comment]
You don't need to specify `SetVisualEmit(false);` anymore, was updated in a recent commit, safe to remove.
You'll also need to add the corresponding methods to the interface IWorldEntity.

**Comment by ChargeIn** [comment]
Since the original initialize is also not in the interface, should I add it as well?

**Comment by Rawaho** [comment]
Honestly the old method can be removed and be replaced with Initialise and SetVisualInfo.
Eventually I expect there to be a `Initialise(ICreatureInfo)` or something to replace.

**Comment by Rawaho** [comment]
Looks good, thank you for the PR and contribution 👍

**Pull request merged**
