### PR TITLE
Web integration

### PR DESCRIPTION
**Pull request by VoidEssy**
Simple template that allows you to run registration page and check the server status on a website. Done in order to simplify user registration and allow users to actually see if server is up and running.

Building it and running it is completely optional but should make it a lot easier for non-tech users to setup and run the emu.

NOTE: At present will check status of only one Server

### CODE REVIEW

**Comment by kirmmin** [comment]
I have been unsuccessful in getting this work so far. I'm not sure if I'm doing something obvious, wrong, but I am unable to create accounts. The AuthServer.json file has been updated, but it doesn't seem to use it? Not sure if it's looking for the file elsewhere, or something?
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at NexusForever.Shared.Extensions.UseConfiguration(DbContextOptionsBuilder optionsBuilder, IDatabaseConfiguration databaseConfiguration, DatabaseType databaseType) in C:\Users\Admin\Documents\NexusForever\Source\NexusForever.Shared\Extensions.cs:line 24
   at NexusForever.Shared.Database.Auth.Model.AuthContext.OnConfiguring(DbContextOptionsBuilder optionsBuilder) in C:\Users\Admin\Documents\NexusForever\Source\NexusForever.Shared\Database\Auth\Model\AuthContext.cs:line 28
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.EntryWithoutDetectChanges[TEntity](TEntity entity)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState[TEntity](TEntity entity, EntityState entityState)
   at NexusForever.Shared.Database.Auth.AuthDatabase.CreateAccount(String email, String password) in C:\Users\Admin\Documents\NexusForever\Source\NexusForever.Shared\Database\Auth\AuthDatabase.cs:line 65
   at MainSite.Controllers.HomeController.Register(AccountBaseModel newUser) in C:\Users\Admin\Documents\NexusForever\Source\MainSite\Controllers\HomeController.cs:line 36
```

Additionally, there doesn't appear to be a straightforward way to bind an address. A config for this would help (or some instructions), I am currently stealing the line from the WorldServer WebServer `.UseUrls("<URL>")`.

**Comment by VoidEssy** [comment]
Unfortunately i can't seem to be able to reproduce the issue on my local setup. It looks like it fails to get the AuthServer connection string even thought it should if it shares same root as the rest of the server. I'm puzzled lost and confused plus I can't seem to be able to reproduce the issue on my local machine.

**Comment by VoidEssy** [comment]
Alright thanks to Krimmin for noticing the issue, it's not fixed and this is the solution for now until better option arises (aka code gets cleaned up), you need to have a copy of AuthServer.Json in the root folder for it to run properly or it has to be in a big pile with the rest of the stuff which i think is messier.... Down the line better / more flexible solution is intended.

**Comment by VoidEssy** [comment]
Yeah would of been nice to know about the mandatory lower-case in WS Client :D But crisis averted! Please don't tell me same thing is with passwords :(

**Pull request closed without merging**
