### PR TITLE
Entity/Player: Fix Teleport crash when server is loading target zone

### PR DESCRIPTION
**Pull request by kirmmin**

### CODE REVIEW

**Comment by Rawaho** [comment]
A command really should check for the teleport before calling TeleportTo and show the error message to the player.
The TeleportTo should throw an exception.

**Comment by kirmmin** [comment]
@Rawaho: Thanks. I was a little unsure the best way to handle this, but I can convert it to that pretty simply. Give me a few :)

**Comment by kirmmin** [comment]
~Updated. Thanks for the quick review.~

Edit: Thought of another way of Teleporting. 1 moment.

**Comment by kirmmin** [comment]
Updated. Again. Should be good now ;)

**Pull request merged**
